// Mocks generated by Mockito 5.4.6 from annotations
// in studioghibli/test/screens/list/movie_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:studioghibli/repository/movie_repository.dart' as _i2;
import 'package:studioghibli/screens/list/movie_list_bloc.dart' as _i3;
import 'package:studioghibli/screens/list/movie_list_event.dart' as _i7;
import 'package:studioghibli/screens/list/movie_list_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMovieRepositoryInterface_0 extends _i1.SmartFake
    implements _i2.MovieRepositoryInterface {
  _FakeMovieRepositoryInterface_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListBloc extends _i1.Mock implements _i3.MovieListBloc {
  @override
  _i2.MovieRepositoryInterface get movieRepository =>
      (super.noSuchMethod(
            Invocation.getter(#movieRepository),
            returnValue: _FakeMovieRepositoryInterface_0(
              this,
              Invocation.getter(#movieRepository),
            ),
            returnValueForMissingStub: _FakeMovieRepositoryInterface_0(
              this,
              Invocation.getter(#movieRepository),
            ),
          )
          as _i2.MovieRepositoryInterface);

  @override
  set movieRepository(_i2.MovieRepositoryInterface? value) =>
      super.noSuchMethod(
        Invocation.setter(#movieRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.MovieListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i4.MovieListState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i4.MovieListState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.MovieListState);

  @override
  _i6.Stream<_i4.MovieListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.MovieListState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i4.MovieListState>.empty(),
          )
          as _i6.Stream<_i4.MovieListState>);

  @override
  void add(_i7.MovieListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.MovieListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.MovieListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.MovieListEvent>(
    _i8.EventHandler<E, _i4.MovieListState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i7.MovieListEvent, _i4.MovieListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i7.MovieListEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i4.MovieListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
