// Mocks generated by Mockito 5.4.6 from annotations
// in studioghibli/test/repository/movie_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:studioghibli/models/movie.dart' as _i5;
import 'package:studioghibli/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  set client(_i2.Client? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i5.Movie>> getMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getMovies, []),
            returnValue: _i4.Future<List<_i5.Movie>>.value(<_i5.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Movie>>.value(
              <_i5.Movie>[],
            ),
          )
          as _i4.Future<List<_i5.Movie>>);

  @override
  _i4.Future<_i5.Movie?> getMovie(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovie, [id]),
            returnValue: _i4.Future<_i5.Movie?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Movie?>.value(),
          )
          as _i4.Future<_i5.Movie?>);
}
